### ISSUE TITLE
German added

### ISSUE THREAD

**Issue by Justman10000** [magrigry/discord-auth#1]
I have German added... The package is available here:

https://mega.nz/folder/YU5xTASQ#M8e-fyK0mqgqYEktzNgqBg

**Comment by magrigry** [comment]
Thanks, done https://market.azuriom.com/resources/62/updates

Btw feel free to use the pull request function so I don't even need to add them by my self :)

**Comment by Justman10000** [comment]
> 
> 
> Thanks, done https://market.azuriom.com/resources/62/updates
> 
> Btw feel free to use the pull request function so I don't even need to add them by my self :)

Yes, I would have, but we don't have upload rights, which we need to upload folders, as you cannot suggest creating folders!
