### ISSUE TITLE
Bonjour, j’ai un problème.

### ISSUE THREAD

**Issue by mo-gd** [magrigry/discord-auth#2]
Bonjour quand je me login avec disocrd sa ne fait rien du tou :/
https://saoniku.xyz/
voila mon site 
Merci

**Comment by magrigry** [comment]
Bonjour, est-ce que tu as bien configuré l’URL de redirection sur github ?

**Comment by mo-gd** [comment]
Autant pour moi, tout marche bien, super plugin !
